<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="row">
          <div class="col">
            <h3 class="text-dark text-center mb-5">Cadastro realizado com sucesso!</h3>
          </div>
        </div>

          
        <script>
          // setTimeout(function() {
          //   window.location.href = "/";
          // }, 10000); // 3 minutos

          //setTimeout();
        </script>
            
         
        


         <div class="row">
          <div class="col">
            <a href="/" class="btn btn-info btn-block btn-login m-auto mt-3">Voltar e fazer login!</a>
          </div>
        </div> 

      </div>
    </div>
  </div>
</div>



    
  