<section class="botoões">
  <div class="container">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div class="row">
          
            <?php if($_SESSION['login'] == 'logado') { ?>
              <div class="col-md-5 d-flex align-items-center">
                <h3 id="nomeH3" class="or or1 ml-auto pt-3 telaGrande"> Olá <?=$_SESSION['nome']?></i></h3>
                <h3  class="or or1 ml-auto justify-content-center telaPequena pr-2"> Olá <?=$_SESSION['nome']?></i></h3>
             </div>
            <?php } ?>
            
              <?php if($_SESSION['login'] == '') { ?>
                <div class="col-md-5 d-flex align-items-center">
                  <h3 class="or or1 ml-auto pt-2 mt-1 telaGrande comecarPedido">Começar o Pedido</h3>
                  <h3 class="or or1 m-auto pt-2 mt-1 justify-content-center telaPequena">Começar o Pedido</h3>
                </div>
              <?php } ?>
          
          <div class="col-md-7 d-flex align-items-center justify-content-center">
            <a href="/entregaBuscar" class="telaGrande btn btn-danger">Entrega</a>
            <h3 class=" telaGrande or or2 pl-3 pr-3">ou</h3>
            <a href="/entregaBuscar" class=" telaGrande btn btn-danger">Retirar na Loja</a>
          </div>
        </div>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
</section>

<!-- Exibido apenas em telas pequenas-->
<section class="telaPequena">
  <div class="container">
  
    <div class="row">
      <div class="col-md-12 d-flex align-items-center justify-content-center">
      <a href="/entregaBuscar" class="btn btn-danger">Entrega</a>
      </div>
      <div class="col-md-12 d-flex align-items-center justify-content-center mt-1">
        <h3 class="or or2 pl-3 pr-3 ">ou</h3>
      </div>
      <div class="col-md-12 d-flex align-items-center justify-content-center">
      <a href="/entregaBuscar" class="btn btn-danger">Retirar na Loja</a>
      </div>
    </div>

  </div>
</section><!-- Exibido apenas em telas pequenas-->

<!-- Exibido em Tela Grange -->
<section class="imagensPzzaria pt-5 telaGrande">
  <div class="container">
    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-10">
        <img class="teste2 img-fluid shadow rounded float-left" src="img/imgPrincipal.jpg" alt=""></img>
        <img class="teste img-fluid shadow rounded float-right mb-3" src="img/imgLateral1.jpg" alt=""></img>
        <img class="teste img-fluid shadow rounded float-right" src="img/imgLateral2.jpg" alt=""></img>
        <img class="img-fluid shadow rounded mt-2" src="img/borda.jpg" alt=""></img>
      </div>
      <div class="col-md-1"></div>
    </div>
  </div>
</section><!-- Exibido em Tela Grange -->

<!-- Exibido apenas em telas pequenas-->
<section class="imagensPzzaria pt-5 telaPequena">
  <div class="container">
    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-10">
        <img class="teste2 img-fluid shadow rounded float-left" src="img/imgPrincipalPequena.jpg" alt=""></img>
        <img class="img-fluid shadow rounded mt-2 pt-2" src="img/imgLateralPequena1.jpg" alt=""></img>
        <img class="img-fluid shadow rounded mt-2 pt-2" src="img/imgLateralPequena2.jpg" alt=""></img>
      </div>
      <div class="col-md-1"></div>
    </div>
  </div>
</section><!-- Exibido apenas em telas pequenas-->

<!-- Exibido apenas em telas pequenas-->
<section class="telaPequena mt-5">
  <div class="container">
    <div class="row">
      <div class="col-md-12 d-flex align-items-center justify-content-center">
        <button class="btn btn-danger">Cardápio</button>
      </div>
      <div class="col-md-12 d-flex align-items-center justify-content-center mt-1">
        <button class="btn btn-danger" data-toggle="modal" data-target="#loginModal">Login</button>
      </div>
      <div class="col-md-12 d-flex align-items-center justify-content-center mt-1">
        <button class="btn btn-danger">Inscrever-se</button>
      </div>
  </div>
</section><!-- Exibido apenas em telas pequenas-->


<a class="wpp-float d-flex justify-content-center d-flex align-items-center" href="https://api.whatsapp.com/send?phone=5519999999999&text=Pizzaria%20do%20Luigi" target="_blank">
  <i class="fab fa-whatsapp d-flex justify-content-center d-flex align-items-center mr-2"></i>
  <small class="d-flex justify-content-center d-flex align-items-center">PEÇA PELO ZAP</small> 
</a>
  



    


