<!--Sessao Acompamhar -->
<div class="container">
	<div class="bg-info shadow mb-4 d-flex" style="height: 50px;">
		<h4 class="text-white m-auto">Acompanhar</h4>
	</div>


	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6 text-center">
				
			<h3 class="text-info mb-4 telaGrande mt-3">Digite o Códico da Sua Compra</h3>
			<h5 class="text-info mb-4 telaPequena ml-2">Digite o Códico da Sua Compra</h5>

			<form action="/acompanhar" method="post" class="m-auto col-9">
				<input name="codico" type="number" class="form-control" required placeholder="Digite o códico da compra aqui...">
				
					<button type="submit" class="btn btn-info mt-2 w-100">OK</button>
				
				
			</form>
		</div>
		<div class="col-md-3"></div>

	</div>





	<div class="row">

	'<div class="col-md-3"></div>

		<?php 
			if(isset($_POST['codico'])) {
				$codico = $_POST['codico'];
			}
		?>
		
		<?php $p = 0; ?>	
		<?php foreach($this->view->pedidos as $id_pedido => $pedido) { ?>
			<?php if(isset($_POST['codico']) && $pedido['id_pedido'] == $codico) { ?>
				<?php $p = 1; ?>
				<div class="col-md-6 mb-4 mt-4 border-bottom pb-5 divPedidos">
					<div class="row">

					<div class="table-responsive" >
						<div class="col-md-12 mt-3 mb-2 divPedidosTabela ">
							<table id="areaToPrint_<?=$pedido['id_pedido']?>" class="table table-striped table-bordered divPedidosTabela">
							<thead class="bg-secondary">
								<tr>
								<th class="text-white" scope="col">Pedido</th>
								<th class="text-white" scope="col"># <?=$pedido['id_pedido']?></th>
				
								</tr>
							</thead>
							
							<tbody class="">
								<tr >
									<th class="text-dark" scope="row">Tipo</th>
									<td class="text-secondary"><?=$pedido['tipo']?></td>
								</tr>
								<tr>
									<th class="text-dark" scope="row">Rua</th>
									<td class="text-secondary"><?=$pedido['rua']?></td>
								</tr>
								
								<tr>
									<th class="text-dark" scope="row">Numero</th>
									<td class="text-secondary"><?=$pedido['numero']?></td>
								</tr>
								
								<tr>
									<th class="text-dark" scope="row">Bairro</th>
									<td class="text-secondary"><?=$pedido['bairro']?></td>
								</tr>
								
								<tr>
									<th class="text-dark" scope="row">Telefone</th>
									<td class="text-secondary"><?=$pedido['telefone']?></td>
								</tr>
								<tr>
									<th class="text-dark" scope="row">Total</th>
									<td class="text-secondary">R$ <?=number_format($pedido['total'], 2, ',', '')?></td>
								</tr>
								<tr>
									<th class="text-dark" scope="row">Status</th>
									<td class="text-success"><?=$pedido['status']?></td>
								</tr>
								<tr>
									<th class="text-dark" scope="row">Data</th>
									<td class="text-secondary"><?=$pedido['data']?></td>
								</tr>
								<tr class=" verMais verMais_<?=$pedido['id_pedido']?>">
									<th class="text-dark" scope="row">Info.</th>
									<td class="text-secondary"><?=$pedido['info_adicionais']?></td>
								</tr>
								<?php foreach($this->view->produtos_pedidos as $id_produto => $produto) { ?>
									<?php if($produto['id_pedido'] == $pedido['id_pedido']) { ?>

										<tr class=" verMais verMais_<?=$pedido['id_pedido']?>">
											<th class="text-dark" scope="row"><img src="img/imgProdutos/<?=$produto['id_produto']?>/<?=$produto['img']?>" alt="" width="90" height="90"></th>
											<td class="text-secondary"><b><?=$produto['nome']?></b> <?php if($produto['tamanho'] != ''){echo '<br>';}?> <?=$produto['tamanho']?><br>Qnt: <?=$produto['quantidade']?><br>R$ <?=number_format($produto['total'], 2, ',', '')?></td>
										
										</tr>
									<?php } ?>
								<?php } ?>	
								
							
							</tbody>
							</table>
							
						</div>


					</div>
						
					</div>
				</div>
			<?php } ?>

			
		<?php } ?>

		<?php if(isset($_POST['codico']) && $p == 0) {?>	

			<div class="container">
				<div class="row">
					<div class="col-12">
						<h4 class="text-danger mt-5 text-center telaGrande"><i class="fas fa-exclamation-triangle"></i> Essa Compra Não Existe, Verifique Se Digitou o Códico Corretamente!</h4>
						<h5 class="text-danger mt-3 text-center telaPequena"><i class="fas fa-exclamation-triangle"></i> Essa Compra Não Existe, Verifique Se Digitou o Códico Corretamente!</h5>
					</div>
				</div>
			</div>


		<?php } ?>

	</div>
</div>

<?php if(count($this->view->pedidos) < 1) { ?>
	<div style="margin-bottom: 250px;"></div>
	
<?php } ?>