<!--Inicio Cardápio -->
<div class="container cardápio telaAdm">
	<div class="row">
		<div class="col-md-1"></div>
		
		<div class="col-md-10">
			
			<h3 class="text-info mb-4 telaGrande mt-3"><i class="fas fa-user-cog"></i> Tela do Administrador</h3>
			<h5 class="text-info mb-4 telaPequena ml-2"><i class="fas fa-user-cog"></i> Tela do Administrador</h5>
      		
			<div class="d-flex justify-content-center" onclick="locationGerenciarCardapio()" style="cursor: pointer">
				<div class="card cardImgTexto">
				<div class="card-body" onmouseleave="$('.h31').css('color', '#17a2b7');" onmouseenter="$('.h31').css('color', 'white');">
					<a  href="/gerenciarCardapio">
						<h4 class="h31 ml-4 telaGrande" style="color: #17a2b7"><i class="fas fa-tasks mr-3"></i>Gerenciar Cardápio</h4>
						<h4 class="h31 telaPequena" style="color: #17a2b7"><i class="fas fa-tasks mr-3"></i>Gerenciar Cardápio</h4>
				  	</a>
				</div>
				</div>
			</div>

			<div class="d-flex justify-content-center" onclick="locationGerenciarPedidos()" style="cursor: pointer">
				<div class="card cardImgTexto">
				<div class="card-body" onmouseleave="$('.h32').css('color', '#17a2b7');" onmouseenter="$('.h32').css('color', 'white');">
					<a href="/gerenciarPedidos">
						<h4 class="h32  ml-4 telaGrande" style="color: #17a2b7"><i class="fas fa-tasks mr-3"></i>Gerenciar Pedidos</h4>
						<h4 class="h32  telaPequena" style="color: #17a2b7"><i class="fas fa-tasks mr-3"></i>Gerenciar Pedidos</h4>

					</a>
				</div>
				</div>
			</div>

			<div class="d-flex justify-content-center" onclick="locationGerenciarUsuarios()" style="cursor: pointer">
				<div class="card cardImgTexto">
				<div class="card-body"  onmouseleave="$('.h33').css('color', '#17a2b7');" onmouseenter="$('.h33').css('color', 'white');">
					<a href="/gerenciarUsuarios">
						<h4 class="h33 ml-4 telaGrande" style="color: #17a2b7"><i class="fas fa-tasks mr-3"></i>Gerenciar Usuários</h4>
						<h4 class="h33 telaPequena" style="color: #17a2b7"><i class="fas fa-tasks mr-3"></i>Gerenciar Usuários</h4>

					</a>
				</div>
				</div>
			</div>

			<div class="d-flex justify-content-center" onclick="locationGerenciarEstoque()" style="cursor: pointer">
				<div class="card cardImgTexto">
				<div class="card-body"  onmouseleave="$('.h35').css('color', '#17a2b7');" onmouseenter="$('.h35').css('color', 'white');">
					<a href="/gerenciarEstoque">
						<h4 class="h35 ml-4 telaGrande" style="color: #17a2b7"><i class="fas fa-tasks mr-3"></i>Gerenciar Estoque</h4>
						<h4 class="h35 telaPequena" style="color: #17a2b7"><i class="fas fa-tasks mr-3"></i>Gerenciar Estoque</h4>

					</a>
				</div>
				</div>
			</div>


			

		</div>
		<div class="col-md-1"></div>
	</div>
</div><!--Fim Cardápio -->