<!--Inicio Cardápio -->
<div class="container cardápio telaAdm">
	<div class="row">
		<div class="col-md-1"></div>
		
		<div class="col-md-10">
			
			<h3 class="text-info mb-4 telaGrande mt-3"><i class="fas fa-users-cog"></i> Gerenciar Usuários</h3>
			<h5 class="text-info mb-4 telaPequena ml-2"><i class="fas fa-users-cog"></i> Gerenciar Usuários</h5>
      		
			<div class="d-flex justify-content-center" onclick="locationAdicionarUsuario()" style="cursor: pointer">
				<div class="card cardImgTexto">
				<div class="card-body" onmouseleave="$('.h31').css('color', '#17a2b7');" onmouseenter="$('.h31').css('color', 'white');">
					<a  href="/adicionarUsuario">
						<h4 class="h31 ml-4 telaGrande" style="color: #17a2b7"><i class="fas fa-user-plus mr-3"></i>Adicionar Usuário</h4>
						<h4 class="h31 telaPequena" style="color: #17a2b7"><i class="fas fa-user-plus mr-3"></i>Adicionar Usuário</h4>
				  	</a>
				</div>
				</div>
			</div>

			<div class="d-flex justify-content-center" onclick="locationRemoverUsuario()" style="cursor: pointer">
				<div class="card cardImgTexto">
				<div class="card-body" onmouseleave="$('.h32').css('color', '#17a2b7');" onmouseenter="$('.h32').css('color', 'white');">
					<a href="/removerUsuario">
						<h4 class="h32  ml-4 telaGrande" style="color: #17a2b7"><i class="fas fa-user-times mr-3"></i>Remover usuário</h4>
						<h4 class="h32  telaPequena" style="color: #17a2b7"><i class="fas fa-user-times mr-3"></i>Remover Usuário</h4>

					</a>
				</div>
				</div>
			</div>

			<div class="d-flex justify-content-center" onclick="locationAtualizarUsuario()" style="cursor: pointer">
				<div class="card cardImgTexto">
				<div class="card-body"  onmouseleave="$('.h33').css('color', '#17a2b7');" onmouseenter="$('.h33').css('color', 'white');">
					<a href="/atualizarUsuario">
						<h4 class="h33 ml-4 telaGrande" style="color: #17a2b7"><i class="fas fa-user-edit mr-3"></i>Atualizar Usuário</h4>
						<h4 class="h33 telaPequena" style="color: #17a2b7"><i class="fas fa-user-edit mr-3"></i></i>Atualizar Usuário</h4>

					</a>
				</div>
				</div>
			</div>
			
			<div class="d-flex justify-content-center" onclick="locationAdministrador()" style="cursor: pointer">
				<div class="card cardImgTexto">
				<div class="card-body"  onmouseleave="$('.h34').css('color', '#17a2b7');" onmouseenter="$('.h34').css('color', 'white');">
					<a href="/administrador">
						<h4 class="h34 ml-4 telaGrande" style="color: #17a2b7"><i class="far fa-hand-point-left mr-3 ml-1"></i>Página Anterior</h4>
						<h4 class="h34 telaPequena" style="color: #17a2b7"><i class="far fa-hand-point-left mr-3 ml-1"></i></i>Página Anterior</h4>

					</a>
				</div>
				</div>
			</div>
			

		</div>
		<div class="col-md-1"></div>
	</div>
</div><!--Fim Cardápio -->