<script>
	

   function modalExcluirUsuario(id) {
	   console.log(id);
	   $("#modalExcluirUsuario").modal('show');
	   document.getElementById('excluirUsuario').value = id;
   }

   $(window).on("load", function(){

		var query =location.search.slice(1)
		var partes = query.split('&');
		var data = {};
		partes.forEach(function (parte) {
			var chaveValor = parte.split('=');
			var chave = chaveValor[0];
			var valor = chaveValor[1];
			data[chave] = valor;
		});


		if (data['error'] == 'false') {
			$('.msgAtualizar_'+data['id']).html('Usuário Atualizado com sucesso!');
		}
		if (data['error'] == 'true') {
			$('.msgError_'+data['id']).html('Erro ao atualizar usuário!');
		}
		
	});

	$(function() {
		$(".formAtualizaUsuario").hide();

	})

	function mostrarFormAtualizaUsuario(id) {
		$(".formAtualizaUsuario_"+id).show();
		$(".btnEditarUsuario_"+id).hide();
		
	
	}
	function esconderFormAtualizaUsuario(id) {
		$(".formAtualizaUsuario_"+id).hide();
		$(".btnEditarUsuario_"+id).show();
		
	}
   

</script>


<?php
	 $tipo = 'ingrediente';
    if (isset($_POST["tipo"])){
        $tipo = $_POST["tipo"];
    }
?>
<!--Sessao Pedidos -->
<div class="container">

	<div class="bg-info shadow mb-4 d-flex" style="height: 50px;">
		<h4 class="text-white m-auto">Tipo: <?=ucfirst($tipo)?></h4>
	</div>

	<div class="row">
		<form class="form-group col-md-3" id="formUsuarios" action="#" method="POST" >
			<select class="form-control" name="tipo" onchange="document.getElementById('formUsuarios').submit()">
				<option>Filtro por TIpo</option>
				<option value="ingrediente">Ingrediente</option>
			<option value="bebida">Bebida</option>
			<option value="sobremesa">Sobremesa</option>
			</select>
		</form>
	</div>

	
	<div class="row">
		
		
		<?php foreach($this->view->lista_estoque as $id_estoque => $estoque) { ?>
			<?php if($estoque['tipo'] != $tipo) { continue; }?>
			<div class="col-md-4 mb-4 mt-4 border-bottom pb-5 divPedidos">
				<div class="row">

					<div class="table-responsive" >
						<div class="col-md-12 mt-3 mb-2 divPedidosTabela ">
							<table class="table table-striped table-bordered divPedidosTabela">
							<thead class="bg-secondary">
								<tr>
								<th class="text-white" scope="col">Estoque</th>
								<th class="text-white" scope="col"># <?=$estoque['id_estoque']?></th>
				
								</tr>
							</thead>
							
							<tbody class="">
								<tr >
									<th class="text-dark" scope="row">Nome</th>
									<td class="text-secondary"><?=$estoque['nome']?></td>
								</tr>
								<tr class="userEmail">
									<th class="text-dark" scope="row">Quentidade</th>
									<td class="text-secondary"><?=$estoque['quantidade']?></td>
								</tr>
								
								<tr>
									<th class="text-dark" scope="row">Tipo</th>
									<td class="text-secondary"><?=ucfirst($estoque['tipo'])?></td>
								</tr>
							</tbody>
							</table>
							<div class="row"> 
								<div class="col-12 mt-2">
									<button onclick="mostrarFormAtualizaUsuario(<?=$estoque['id_estoque']?>)" class="btn btn-info btnEditarUsuario_<?=$estoque['id_estoque']?> w-100 p-1">Editar</button>
								</div>
							</div>
							<h6 class="msgAtualizar_<?=$estoque['id_estoque']?> text-success text-center btnEditarUsuario_<?=$estoque['id_estoque']?>"></h6>
							<h6 class="msgError_<?=$estoque['id_estoque']?> text-danger text-center btnEditarUsuario_<?=$estoque['id_estoque']?>"></h6>


							<div class="row formAtualizaUsuario formAtualizaUsuario_<?=$estoque['id_estoque']?>">
								<form action="atualizarUsuarioBanco" method="post" class="formAddProduto col-12">
									<div class="custom-area">
										<input name="id_usuario" type="hidden" value="<?=$estoque['id_estoque']?>">
										<label class="text-info font-weight-bold" for="validationServer03">Nome:</label>
										<input name="nome" type="text" class="form-control" id="validationServer03" value="<?=$estoque['nome']?>" placeholder="Digite o nome...">

										<label class="text-info font-weight-bold mt-2" for="validationServer03">Quantidade:</label>
										<input name="email" type="email" class="form-control" id="validationServer03" value="<?=$estoque['quantidade']?>" placeholder="Digite e-mail...">

										<label class="text-info font-weight-bold mt-2" for="validationServer03">Tipo:</label>
										<select class="form-control" name="tipo">
											<option value="<?=$usuario['tipo']?>">Selecione o TIpo</option>
											<option value="ingrediente">Ingrediente</option>
											<option value="bebida">Bebida</option>
											<option value="sobremesa">Sobremesa</option>
			
										</select>

		
									</div>
									<button type="submit" class="btn btn-info p-1 w-100 mt-4">Atualizar</button>

									
								</form>
								<div class="col-12">
									<button onclick="esconderFormAtualizaUsuario(<?=$estoque['id_estoque']?>)" class="btn btn-danger p-1 w-100 mt-3">Cancelar</button>
								</div>
								
							
								
						
							</div>
								
						</div>
					</div>
					
				</div>
			</div>
		<?php } ?>

	</div>
</div>


<!-- Modal Fechar Pedido -->
<div class="modal fade" id="modalExcluirUsuario" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered" role="document">
	<div class="modal-content">
	<div class="modal-header">
		<h4 class="modal-title" id="exampleModalLongTitle">Tem certeza que deseja excluir esse usuario ?</h4>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		<span aria-hidden="true">&times;</span>
		</button>
	</div>
	<div id="registro" class="modal-body text-danger">
		Cuidado! Esse usuuario será excluido!
	</div>
	
	<div class="modal-footer">
	
		<form action="/removerUsuarioBanco" method="post">
			<input id="excluirUsuario" type="hidden" name="id_usuario">
			<div class="row">
				<button type="submit" class="btn btn-info col-5">Sim</button>
				<div class="col-2"></div>	
				<button type="button" class="btn btn-danger col-5" data-dismiss="modal">Cancelar</button>
			</div>	
		
		</form>
	
	</div>
			
	</div>
	</div>
</div>
</div><!-- Fim do Modal  -->

<!-- Modal Sucesso -->
<div class="modal fade" id="modalUsuarioRemovidoSucesso" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<h4 class="modal-title text-success" id="exampleModalLongTitle"></h4>
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
			<span aria-hidden="true">&times;</span>
			</button>
		</div>
		
		<div class="row">
			<div class="col-1"></div>
			<div id="registro" class="modal-body text-success col-11">
				<h4> Usuario removido com sucesso!</h4>
			</div>
		</div>

		<div class="modal-footer">
		</div>
	</div>
</div>
</div><!-- Fim do Modal  -->