<script>
	$(function() {
		$(".verMais").hide();
		$(".btnVerMenos").hide();
	})

	function verMais(id) {
		$(".verMais_"+id).show();
		$(".btnVerMenos_"+id).show();
		$(".btnVerMais_"+id).hide();
	}
	function verMenos(id) {
		$(".verMais_"+id).hide();
		$(".btnVerMenos_"+id).hide();
		$(".btnVerMais_"+id).show();
		
	}


    function printDiv(id) {
        var divToPrint = document.getElementById('areaToPrint_'+id);
        newWin = window.open("");
        newWin.document.write(divToPrint.outerHTML);
        newWin.print();
        newWin.close();
   }

   function modalFecharPedido(id) {
	   console.log(id);
	   $("#modalFecharPedido").modal('show');
	   document.getElementById('fecharPedido').value = id;
   }

   function modalExcluirPedido(id) {
	   console.log(id);
	   $("#modalExcluirPedido").modal('show');
	   document.getElementById('excluirPedido').value = id;
   }

   $(window).on("load", function(){

		var query =location.search.slice(1)
		var partes = query.split('&');
		var data = {};
		partes.forEach(function (parte) {
			var chaveValor = parte.split('=');
			var chave = chaveValor[0];
			var valor = chaveValor[1];
			data[chave] = valor;
		});

		console.log(data['pedido']);

		if (data['pedido'] == 'fechado') {
			console.log('entrou aqui');
			$('#modalPedidoFechadoSucesso').modal('show');

			setTimeout( function mudarURL2() {
			//window.location = '/removerProdutoPizza?produto=#/'
			window.location.replace('/pedidosAbertos');
			}, 1500)

			
		}

		if (data['pedido'] == 'excluido') {
			console.log('entrou aqui');
			$('#modalPedidoExcluidoSucesso').modal('show');

			setTimeout( function mudarURL2() {
			//window.location = '/removerProdutoPizza?produto=#/'
			window.location.replace('/pedidosAbertos');
			}, 1500)

			
		}
	});
   

</script>



<!--Sessao Pedidos -->
<div class="container">
	<div class="bg-info shadow mb-4 d-flex" style="height: 50px;">
		<h4 class="text-white m-auto">Pedidos em aberto</h4>
	</div>

	<div class="row">
		
		<?php foreach($this->view->pedidos as $id_pedido => $pedido) { ?>
			<div class="col-md-4 mb-4 mt-4 border-bottom pb-5 divPedidos">
				<div class="row">

				<div class="table-responsive" >
					<div class="col-md-12 mt-3 mb-2 divPedidosTabela ">
						<table id="areaToPrint_<?=$pedido['id_pedido']?>" class="table table-striped table-bordered divPedidosTabela">
						<thead class="bg-secondary">
							<tr>
							<th class="text-white" scope="col">Pedido</th>
							<th class="text-white" scope="col"># <?=$pedido['id_pedido']?></th>
			
							</tr>
						</thead>
						
						<tbody class="">
							<tr >
								<th class="text-dark" scope="row">Tipo</th>
								<td class="text-secondary"><?=$pedido['tipo']?></td>
							</tr>
							<tr>
								<th class="text-dark" scope="row">Rua</th>
								<td class="text-secondary"><?=$pedido['rua']?></td>
							</tr>
							
							<tr>
								<th class="text-dark" scope="row">Numero</th>
								<td class="text-secondary"><?=$pedido['numero']?></td>
							</tr>
							
							<tr>
								<th class="text-dark" scope="row">Bairro</th>
								<td class="text-secondary"><?=$pedido['bairro']?></td>
							</tr>
							
							<tr>
								<th class="text-dark" scope="row">Telefone</th>
								<td class="text-secondary"><?=$pedido['telefone']?></td>
							</tr>
							<tr>
								<th class="text-dark" scope="row">Total</th>
								<td class="text-secondary">R$ <?=number_format($pedido['total'], 2, ',', '')?></td>
							</tr>
							<tr>
								<th class="text-dark" scope="row">Status</th>
								<td class="text-success"><?=$pedido['status']?></td>
							</tr>
							<tr>
								<th class="text-dark" scope="row">Data</th>
								<td class="text-secondary"><?=$pedido['data']?></td>
							</tr>
							<tr class=" verMais verMais_<?=$pedido['id_pedido']?>">
								<th class="text-dark" scope="row">Info.</th>
								<td class="text-secondary"><?=$pedido['info_adicionais']?></td>
							</tr>
							<?php foreach($this->view->produtos_pedidos as $id_produto => $produto) { ?>
								<?php if($produto['id_pedido'] == $pedido['id_pedido']) { ?>

									<tr class=" verMais verMais_<?=$pedido['id_pedido']?>">
										<th class="text-dark" scope="row"><img src="img/imgProdutos/<?=$produto['id_produto']?>/<?=$produto['img']?>" alt="" width="90" height="90"></th>
										<td class="text-secondary"><b><?=$produto['nome']?></b> <?php if($produto['tamanho'] != ''){echo '<br>';}?> <?=$produto['tamanho']?><br>Qnt: <?=$produto['quantidade']?><br>R$ <?=number_format($produto['total'], 2, ',', '')?></td>
									
									</tr>
								<?php } ?>
							<?php } ?>	
							
						
						</tbody>
						</table>
						<div class="row"> 
							<div class="col-12 mb-3">
								<button onclick="verMenos(<?=$pedido['id_pedido']?>)" class="btn btn-outline-danger w-100 p-1 btnVerMenos btnVerMenos_<?=$pedido['id_pedido']?>">Ver Menos</button>
							</div>
							<div class="col-12  mb-3">
								<button onclick="verMais(<?=$pedido['id_pedido']?>)" class="btn btn-outline-dark w-100 p-1 btnVerMais_<?=$pedido['id_pedido']?>">Ver Mais...</button>
							</div>
						</div>	

						<div class="row"> 
							<div class="col-4">
								
								<button onclick="modalFecharPedido(<?=$pedido['id_pedido']?>)" class="btn btn-info w-100 p-1">Fechar</button>
								
							</div>

							<div class="col-4">
								<button onclick="printDiv(<?=$pedido['id_pedido']?>)" class="btn btn-secondary w-100 p-1">Imprimir</button>
							</div>
							
							<div class="col-4">
								<button  onclick="modalExcluirPedido(<?=$pedido['id_pedido']?>)" class="btn btn-danger w-100 p-1">Excluir</button>
							</div>

							
						</div>
						
					</div>


				</div>
					
				</div>
			</div>
		<?php } ?>

	</div>
</div>

<?php if(count($this->view->pedidos) < 1) { ?>
	<div style="margin-bottom: 250px;"></div>
	
<?php } ?>	

<!-- Modal Fechar Pedido -->
<div class="modal fade" id="modalFecharPedido" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered" role="document">
	<div class="modal-content">
	<div class="modal-header">
		<h4 class="modal-title" id="exampleModalLongTitle">Tem certeza que deseja fechar esse pedido ?</h4>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		<span aria-hidden="true">&times;</span>
		</button>
	</div>
	<div id="registro" class="modal-body text-danger">
		Cuidado! Esse Pedido será fechado!
	</div>
	
	<div class="modal-footer">
	
		<form action="/fecharPedido" method="post">
			<input id="fecharPedido" type="hidden" name="id_pedido">
			<div class="row">
				<button type="submit" class="btn btn-info col-5">Sim</button>
				<div class="col-2"></div>	
				<button type="button" class="btn btn-danger col-5" data-dismiss="modal">Cancelar</button>
			</div>	
		
		</form>
	
	</div>
			
	</div>
	</div>
</div>
</div><!-- Fim do Modal  -->

<!-- Modal Sucesso -->
<div class="modal fade" id="modalPedidoFechadoSucesso" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<h4 class="modal-title text-success" id="exampleModalLongTitle"></h4>
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
			<span aria-hidden="true">&times;</span>
			</button>
		</div>
		
		<div class="row">
			<div class="col-1"></div>
			<div id="registro" class="modal-body text-success col-11">
				<h4> Pedido fechado com sucesso!</h4>
			</div>
		</div>

		<div class="modal-footer">
		</div>
	</div>
</div>
</div><!-- Fim do Modal  -->

<!-- Modal Excluir Pedido -->
<div class="modal fade" id="modalExcluirPedido" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered" role="document">
	<div class="modal-content">
	<div class="modal-header">
		<h4 class="modal-title" id="exampleModalLongTitle">Tem certeza que deseja excluir esse pedido ?</h4>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		<span aria-hidden="true">&times;</span>
		</button>
	</div>
	<div id="registro" class="modal-body text-danger">
		Cuidado! Esse Pedido será excluido!
	</div>
	
	<div class="modal-footer">
	
		<form action="/excluirPedido" method="post">
			<input id="excluirPedido" type="hidden" name="id_pedido">
			<div class="row">
				<button type="submit" class="btn btn-info col-5">Sim</button>
				<div class="col-2"></div>	
				<button type="button" class="btn btn-danger col-5" data-dismiss="modal">Cancelar</button>
			</div>	
		
		</form>
	
	</div>
			
	</div>
	</div>
</div>
</div><!-- Fim do Modal  -->

<!-- Modal Pedido Excluido Sucesso -->
<div class="modal fade" id="modalPedidoExcluidoSucesso" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<h4 class="modal-title text-success" id="exampleModalLongTitle"></h4>
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
			<span aria-hidden="true">&times;</span>
			</button>
		</div>
		
		<div class="row">
			<div class="col-1"></div>
			<div id="registro" class="modal-body text-success col-11">
				<h4> Pedido excluido com sucesso!</h4>
			</div>
		</div>

		<div class="modal-footer">
		</div>
	</div>
</div>
</div><!-- Fim do Modal  -->